name: CI
on: 
  pull_request:
    branches:
      - '**/**'
jobs:
  build-package:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
      - name: Build Watchers package
        run: |
          flutter pub get
          flutter analyze
          flutter format --set-exit-if-changed .
          flutter test
  build-example-app:
    needs: build-package
    name: Build example app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
      - name: Build example app
        run: |
          cd example
          flutter pub get
          flutter analyze
          flutter format --set-exit-if-changed .
          flutter test
          flutter build web