name: Coverage report
on:
  pull_request:
    branches:
      - '**/**'
  push:
    branches:
      - main
jobs:
  coverage:
    name: generate coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
      - name: Install lcov
        run: |
          sudo apt update
          sudo apt install lcov
      - name: Setup git config
        run: |
          git config user.name "PiotrFLEURY"
          git config user.email "piotr.fleury@gmail.com"
      - name: Checkout report branch
        run: |
          git checkout -b chore/coverage
      - name: Generate lcov.info file
        run: |
          flutter pub get
          flutter test --coverage
      - name: Generate HTML report
        run: |
          mkdir docs
          genhtml -o docs/ coverage/lcov.info
      - name: Commit & push changes
        run: |
          git add .
          git commit -m "chore(coverage): new coverage generated"
          git push -f --set-upstream origin chore/coverage